# Generated by Django 3.2.19 on 2025-06-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20250627_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
